/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedReelsRouteImport } from './routes/_authenticated/reels'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlusRouteImport } from './routes/_authenticated/plus'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedChatsRouteImport } from './routes/_authenticated/chats'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp-webhook'
import { Route as ApiPublicAdminBootstrapRouteImport } from './routes/api/public/admin-bootstrap'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'
import { Route as AuthenticatedPlusReservadosRouteImport } from './routes/_authenticated/plus.reservados'
import { Route as AuthenticatedPlusPersonalizarRouteImport } from './routes/_authenticated/plus.personalizar'
import { Route as AuthenticatedPlusCheckoutRouteImport } from './routes/_authenticated/plus.checkout'
import { Route as AuthenticatedPIdRouteImport } from './routes/_authenticated/p.$id'
import { Route as AuthenticatedGroupsNewRouteImport } from './routes/_authenticated/groups.new'
import { Route as AuthenticatedChatsIdRouteImport } from './routes/_authenticated/chats.$id'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin.security'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminBenefitsRouteImport } from './routes/_authenticated/admin.benefits'
import { Route as ApiPublicDownloadWindowsRouteImport } from './routes/api/public/download.windows'
import { Route as AuthenticatedUUsernameFollowingRouteImport } from './routes/_authenticated/u.$username.following'
import { Route as AuthenticatedUUsernameFollowersRouteImport } from './routes/_authenticated/u.$username.followers'
import { Route as AuthenticatedPlusPersonalizarCatRouteImport } from './routes/_authenticated/plus.personalizar.$cat'
import { Route as AuthenticatedGroupsIdEditRouteImport } from './routes/_authenticated/groups.$id.edit'
import { Route as AuthenticatedAdminUIdRouteImport } from './routes/_authenticated/admin.u.$id'
import { Route as AuthenticatedAdminInspectIdRouteImport } from './routes/_authenticated/admin.inspect.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReelsRoute = AuthenticatedReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlusRoute = AuthenticatedPlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatsRoute = AuthenticatedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminBootstrapRoute = ApiPublicAdminBootstrapRouteImport.update({
  id: '/api/public/admin-bootstrap',
  path: '/api/public/admin-bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlusReservadosRoute =
  AuthenticatedPlusReservadosRouteImport.update({
    id: '/reservados',
    path: '/reservados',
    getParentRoute: () => AuthenticatedPlusRoute,
  } as any)
const AuthenticatedPlusPersonalizarRoute =
  AuthenticatedPlusPersonalizarRouteImport.update({
    id: '/personalizar',
    path: '/personalizar',
    getParentRoute: () => AuthenticatedPlusRoute,
  } as any)
const AuthenticatedPlusCheckoutRoute =
  AuthenticatedPlusCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => AuthenticatedPlusRoute,
  } as any)
const AuthenticatedPIdRoute = AuthenticatedPIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGroupsNewRoute = AuthenticatedGroupsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedGroupsRoute,
} as any)
const AuthenticatedChatsIdRoute = AuthenticatedChatsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedChatsRoute,
} as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBenefitsRoute =
  AuthenticatedAdminBenefitsRouteImport.update({
    id: '/benefits',
    path: '/benefits',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicDownloadWindowsRoute =
  ApiPublicDownloadWindowsRouteImport.update({
    id: '/api/public/download/windows',
    path: '/api/public/download/windows',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedUUsernameFollowingRoute =
  AuthenticatedUUsernameFollowingRouteImport.update({
    id: '/following',
    path: '/following',
    getParentRoute: () => AuthenticatedUUsernameRoute,
  } as any)
const AuthenticatedUUsernameFollowersRoute =
  AuthenticatedUUsernameFollowersRouteImport.update({
    id: '/followers',
    path: '/followers',
    getParentRoute: () => AuthenticatedUUsernameRoute,
  } as any)
const AuthenticatedPlusPersonalizarCatRoute =
  AuthenticatedPlusPersonalizarCatRouteImport.update({
    id: '/$cat',
    path: '/$cat',
    getParentRoute: () => AuthenticatedPlusPersonalizarRoute,
  } as any)
const AuthenticatedGroupsIdEditRoute =
  AuthenticatedGroupsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedGroupsRoute,
  } as any)
const AuthenticatedAdminUIdRoute = AuthenticatedAdminUIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminInspectIdRoute =
  AuthenticatedAdminInspectIdRouteImport.update({
    id: '/inspect/$id',
    path: '/inspect/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/chats': typeof AuthenticatedChatsRouteWithChildren
  '/create': typeof AuthenticatedCreateRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/plus': typeof AuthenticatedPlusRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/benefits': typeof AuthenticatedAdminBenefitsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/chats/$id': typeof AuthenticatedChatsIdRoute
  '/groups/new': typeof AuthenticatedGroupsNewRoute
  '/p/$id': typeof AuthenticatedPIdRoute
  '/plus/checkout': typeof AuthenticatedPlusCheckoutRoute
  '/plus/personalizar': typeof AuthenticatedPlusPersonalizarRouteWithChildren
  '/plus/reservados': typeof AuthenticatedPlusReservadosRoute
  '/u/$username': typeof AuthenticatedUUsernameRouteWithChildren
  '/api/public/admin-bootstrap': typeof ApiPublicAdminBootstrapRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/inspect/$id': typeof AuthenticatedAdminInspectIdRoute
  '/admin/u/$id': typeof AuthenticatedAdminUIdRoute
  '/groups/$id/edit': typeof AuthenticatedGroupsIdEditRoute
  '/plus/personalizar/$cat': typeof AuthenticatedPlusPersonalizarCatRoute
  '/u/$username/followers': typeof AuthenticatedUUsernameFollowersRoute
  '/u/$username/following': typeof AuthenticatedUUsernameFollowingRoute
  '/api/public/download/windows': typeof ApiPublicDownloadWindowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/chats': typeof AuthenticatedChatsRouteWithChildren
  '/create': typeof AuthenticatedCreateRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/plus': typeof AuthenticatedPlusRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/benefits': typeof AuthenticatedAdminBenefitsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/chats/$id': typeof AuthenticatedChatsIdRoute
  '/groups/new': typeof AuthenticatedGroupsNewRoute
  '/p/$id': typeof AuthenticatedPIdRoute
  '/plus/checkout': typeof AuthenticatedPlusCheckoutRoute
  '/plus/personalizar': typeof AuthenticatedPlusPersonalizarRouteWithChildren
  '/plus/reservados': typeof AuthenticatedPlusReservadosRoute
  '/u/$username': typeof AuthenticatedUUsernameRouteWithChildren
  '/api/public/admin-bootstrap': typeof ApiPublicAdminBootstrapRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/inspect/$id': typeof AuthenticatedAdminInspectIdRoute
  '/admin/u/$id': typeof AuthenticatedAdminUIdRoute
  '/groups/$id/edit': typeof AuthenticatedGroupsIdEditRoute
  '/plus/personalizar/$cat': typeof AuthenticatedPlusPersonalizarCatRoute
  '/u/$username/followers': typeof AuthenticatedUUsernameFollowersRoute
  '/u/$username/following': typeof AuthenticatedUUsernameFollowingRoute
  '/api/public/download/windows': typeof ApiPublicDownloadWindowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/chats': typeof AuthenticatedChatsRouteWithChildren
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/plus': typeof AuthenticatedPlusRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reels': typeof AuthenticatedReelsRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/admin/benefits': typeof AuthenticatedAdminBenefitsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/chats/$id': typeof AuthenticatedChatsIdRoute
  '/_authenticated/groups/new': typeof AuthenticatedGroupsNewRoute
  '/_authenticated/p/$id': typeof AuthenticatedPIdRoute
  '/_authenticated/plus/checkout': typeof AuthenticatedPlusCheckoutRoute
  '/_authenticated/plus/personalizar': typeof AuthenticatedPlusPersonalizarRouteWithChildren
  '/_authenticated/plus/reservados': typeof AuthenticatedPlusReservadosRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRouteWithChildren
  '/api/public/admin-bootstrap': typeof ApiPublicAdminBootstrapRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/inspect/$id': typeof AuthenticatedAdminInspectIdRoute
  '/_authenticated/admin/u/$id': typeof AuthenticatedAdminUIdRoute
  '/_authenticated/groups/$id/edit': typeof AuthenticatedGroupsIdEditRoute
  '/_authenticated/plus/personalizar/$cat': typeof AuthenticatedPlusPersonalizarCatRoute
  '/_authenticated/u/$username/followers': typeof AuthenticatedUUsernameFollowersRoute
  '/_authenticated/u/$username/following': typeof AuthenticatedUUsernameFollowingRoute
  '/api/public/download/windows': typeof ApiPublicDownloadWindowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download'
    | '/login'
    | '/admin'
    | '/chats'
    | '/create'
    | '/explore'
    | '/feed'
    | '/groups'
    | '/notifications'
    | '/plus'
    | '/profile'
    | '/reels'
    | '/saved'
    | '/search'
    | '/settings'
    | '/admin/benefits'
    | '/admin/reports'
    | '/admin/security'
    | '/chats/$id'
    | '/groups/new'
    | '/p/$id'
    | '/plus/checkout'
    | '/plus/personalizar'
    | '/plus/reservados'
    | '/u/$username'
    | '/api/public/admin-bootstrap'
    | '/api/public/mp-webhook'
    | '/admin/'
    | '/admin/inspect/$id'
    | '/admin/u/$id'
    | '/groups/$id/edit'
    | '/plus/personalizar/$cat'
    | '/u/$username/followers'
    | '/u/$username/following'
    | '/api/public/download/windows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/login'
    | '/chats'
    | '/create'
    | '/explore'
    | '/feed'
    | '/groups'
    | '/notifications'
    | '/plus'
    | '/profile'
    | '/reels'
    | '/saved'
    | '/search'
    | '/settings'
    | '/admin/benefits'
    | '/admin/reports'
    | '/admin/security'
    | '/chats/$id'
    | '/groups/new'
    | '/p/$id'
    | '/plus/checkout'
    | '/plus/personalizar'
    | '/plus/reservados'
    | '/u/$username'
    | '/api/public/admin-bootstrap'
    | '/api/public/mp-webhook'
    | '/admin'
    | '/admin/inspect/$id'
    | '/admin/u/$id'
    | '/groups/$id/edit'
    | '/plus/personalizar/$cat'
    | '/u/$username/followers'
    | '/u/$username/following'
    | '/api/public/download/windows'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/download'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/chats'
    | '/_authenticated/create'
    | '/_authenticated/explore'
    | '/_authenticated/feed'
    | '/_authenticated/groups'
    | '/_authenticated/notifications'
    | '/_authenticated/plus'
    | '/_authenticated/profile'
    | '/_authenticated/reels'
    | '/_authenticated/saved'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/admin/benefits'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/security'
    | '/_authenticated/chats/$id'
    | '/_authenticated/groups/new'
    | '/_authenticated/p/$id'
    | '/_authenticated/plus/checkout'
    | '/_authenticated/plus/personalizar'
    | '/_authenticated/plus/reservados'
    | '/_authenticated/u/$username'
    | '/api/public/admin-bootstrap'
    | '/api/public/mp-webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/inspect/$id'
    | '/_authenticated/admin/u/$id'
    | '/_authenticated/groups/$id/edit'
    | '/_authenticated/plus/personalizar/$cat'
    | '/_authenticated/u/$username/followers'
    | '/_authenticated/u/$username/following'
    | '/api/public/download/windows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  LoginRoute: typeof LoginRoute
  ApiPublicAdminBootstrapRoute: typeof ApiPublicAdminBootstrapRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
  ApiPublicDownloadWindowsRoute: typeof ApiPublicDownloadWindowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reels': {
      id: '/_authenticated/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AuthenticatedReelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plus': {
      id: '/_authenticated/plus'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof AuthenticatedPlusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chats': {
      id: '/_authenticated/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-bootstrap': {
      id: '/api/public/admin-bootstrap'
      path: '/api/public/admin-bootstrap'
      fullPath: '/api/public/admin-bootstrap'
      preLoaderRoute: typeof ApiPublicAdminBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plus/reservados': {
      id: '/_authenticated/plus/reservados'
      path: '/reservados'
      fullPath: '/plus/reservados'
      preLoaderRoute: typeof AuthenticatedPlusReservadosRouteImport
      parentRoute: typeof AuthenticatedPlusRoute
    }
    '/_authenticated/plus/personalizar': {
      id: '/_authenticated/plus/personalizar'
      path: '/personalizar'
      fullPath: '/plus/personalizar'
      preLoaderRoute: typeof AuthenticatedPlusPersonalizarRouteImport
      parentRoute: typeof AuthenticatedPlusRoute
    }
    '/_authenticated/plus/checkout': {
      id: '/_authenticated/plus/checkout'
      path: '/checkout'
      fullPath: '/plus/checkout'
      preLoaderRoute: typeof AuthenticatedPlusCheckoutRouteImport
      parentRoute: typeof AuthenticatedPlusRoute
    }
    '/_authenticated/p/$id': {
      id: '/_authenticated/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof AuthenticatedPIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/new': {
      id: '/_authenticated/groups/new'
      path: '/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof AuthenticatedGroupsNewRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
    '/_authenticated/chats/$id': {
      id: '/_authenticated/chats/$id'
      path: '/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof AuthenticatedChatsIdRouteImport
      parentRoute: typeof AuthenticatedChatsRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/benefits': {
      id: '/_authenticated/admin/benefits'
      path: '/benefits'
      fullPath: '/admin/benefits'
      preLoaderRoute: typeof AuthenticatedAdminBenefitsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/download/windows': {
      id: '/api/public/download/windows'
      path: '/api/public/download/windows'
      fullPath: '/api/public/download/windows'
      preLoaderRoute: typeof ApiPublicDownloadWindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/u/$username/following': {
      id: '/_authenticated/u/$username/following'
      path: '/following'
      fullPath: '/u/$username/following'
      preLoaderRoute: typeof AuthenticatedUUsernameFollowingRouteImport
      parentRoute: typeof AuthenticatedUUsernameRoute
    }
    '/_authenticated/u/$username/followers': {
      id: '/_authenticated/u/$username/followers'
      path: '/followers'
      fullPath: '/u/$username/followers'
      preLoaderRoute: typeof AuthenticatedUUsernameFollowersRouteImport
      parentRoute: typeof AuthenticatedUUsernameRoute
    }
    '/_authenticated/plus/personalizar/$cat': {
      id: '/_authenticated/plus/personalizar/$cat'
      path: '/$cat'
      fullPath: '/plus/personalizar/$cat'
      preLoaderRoute: typeof AuthenticatedPlusPersonalizarCatRouteImport
      parentRoute: typeof AuthenticatedPlusPersonalizarRoute
    }
    '/_authenticated/groups/$id/edit': {
      id: '/_authenticated/groups/$id/edit'
      path: '/$id/edit'
      fullPath: '/groups/$id/edit'
      preLoaderRoute: typeof AuthenticatedGroupsIdEditRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
    '/_authenticated/admin/u/$id': {
      id: '/_authenticated/admin/u/$id'
      path: '/u/$id'
      fullPath: '/admin/u/$id'
      preLoaderRoute: typeof AuthenticatedAdminUIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inspect/$id': {
      id: '/_authenticated/admin/inspect/$id'
      path: '/inspect/$id'
      fullPath: '/admin/inspect/$id'
      preLoaderRoute: typeof AuthenticatedAdminInspectIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBenefitsRoute: typeof AuthenticatedAdminBenefitsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminInspectIdRoute: typeof AuthenticatedAdminInspectIdRoute
  AuthenticatedAdminUIdRoute: typeof AuthenticatedAdminUIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBenefitsRoute: AuthenticatedAdminBenefitsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminInspectIdRoute: AuthenticatedAdminInspectIdRoute,
  AuthenticatedAdminUIdRoute: AuthenticatedAdminUIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedChatsRouteChildren {
  AuthenticatedChatsIdRoute: typeof AuthenticatedChatsIdRoute
}

const AuthenticatedChatsRouteChildren: AuthenticatedChatsRouteChildren = {
  AuthenticatedChatsIdRoute: AuthenticatedChatsIdRoute,
}

const AuthenticatedChatsRouteWithChildren =
  AuthenticatedChatsRoute._addFileChildren(AuthenticatedChatsRouteChildren)

interface AuthenticatedGroupsRouteChildren {
  AuthenticatedGroupsNewRoute: typeof AuthenticatedGroupsNewRoute
  AuthenticatedGroupsIdEditRoute: typeof AuthenticatedGroupsIdEditRoute
}

const AuthenticatedGroupsRouteChildren: AuthenticatedGroupsRouteChildren = {
  AuthenticatedGroupsNewRoute: AuthenticatedGroupsNewRoute,
  AuthenticatedGroupsIdEditRoute: AuthenticatedGroupsIdEditRoute,
}

const AuthenticatedGroupsRouteWithChildren =
  AuthenticatedGroupsRoute._addFileChildren(AuthenticatedGroupsRouteChildren)

interface AuthenticatedPlusPersonalizarRouteChildren {
  AuthenticatedPlusPersonalizarCatRoute: typeof AuthenticatedPlusPersonalizarCatRoute
}

const AuthenticatedPlusPersonalizarRouteChildren: AuthenticatedPlusPersonalizarRouteChildren =
  {
    AuthenticatedPlusPersonalizarCatRoute:
      AuthenticatedPlusPersonalizarCatRoute,
  }

const AuthenticatedPlusPersonalizarRouteWithChildren =
  AuthenticatedPlusPersonalizarRoute._addFileChildren(
    AuthenticatedPlusPersonalizarRouteChildren,
  )

interface AuthenticatedPlusRouteChildren {
  AuthenticatedPlusCheckoutRoute: typeof AuthenticatedPlusCheckoutRoute
  AuthenticatedPlusPersonalizarRoute: typeof AuthenticatedPlusPersonalizarRouteWithChildren
  AuthenticatedPlusReservadosRoute: typeof AuthenticatedPlusReservadosRoute
}

const AuthenticatedPlusRouteChildren: AuthenticatedPlusRouteChildren = {
  AuthenticatedPlusCheckoutRoute: AuthenticatedPlusCheckoutRoute,
  AuthenticatedPlusPersonalizarRoute:
    AuthenticatedPlusPersonalizarRouteWithChildren,
  AuthenticatedPlusReservadosRoute: AuthenticatedPlusReservadosRoute,
}

const AuthenticatedPlusRouteWithChildren =
  AuthenticatedPlusRoute._addFileChildren(AuthenticatedPlusRouteChildren)

interface AuthenticatedUUsernameRouteChildren {
  AuthenticatedUUsernameFollowersRoute: typeof AuthenticatedUUsernameFollowersRoute
  AuthenticatedUUsernameFollowingRoute: typeof AuthenticatedUUsernameFollowingRoute
}

const AuthenticatedUUsernameRouteChildren: AuthenticatedUUsernameRouteChildren =
  {
    AuthenticatedUUsernameFollowersRoute: AuthenticatedUUsernameFollowersRoute,
    AuthenticatedUUsernameFollowingRoute: AuthenticatedUUsernameFollowingRoute,
  }

const AuthenticatedUUsernameRouteWithChildren =
  AuthenticatedUUsernameRoute._addFileChildren(
    AuthenticatedUUsernameRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedChatsRoute: typeof AuthenticatedChatsRouteWithChildren
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPlusRoute: typeof AuthenticatedPlusRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReelsRoute: typeof AuthenticatedReelsRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedPIdRoute: typeof AuthenticatedPIdRoute
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedChatsRoute: AuthenticatedChatsRouteWithChildren,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPlusRoute: AuthenticatedPlusRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReelsRoute: AuthenticatedReelsRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedPIdRoute: AuthenticatedPIdRoute,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DownloadRoute: DownloadRoute,
  LoginRoute: LoginRoute,
  ApiPublicAdminBootstrapRoute: ApiPublicAdminBootstrapRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
  ApiPublicDownloadWindowsRoute: ApiPublicDownloadWindowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
